-- ESQUELETO BASICO DE UMA TRIGGER
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA -- ANTES OU DEPOIS
FOR EACH ROW -- (PARA CADA LINHA)
BEGIN -> INICIO
    -- TRIGGER FAZ QUALQUER COMANDO SQL
END -> FIM

-- LEMBRE-SE DE USAR DELIMITER