SHOW DATABASES;
CREATE DATABASE AULATRIGGER;
USE AULATRIGGER;

/*
  ESQUELETO
-- ESQUELETO BASICO DE UMA TRIGGER
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA -- ANTES OU DEPOIS
FOR EACH ROW -- (PARA CADA LINHA)
BEGIN -> INICIO
    -- TRIGGER FAZ QUALQUER COMANDO SQL
END -> FIM

-- LEMBRE-SE DE USAR DELIMITER
*/

DROP TABLE BKP_USUARIO;

CREATE TABLE USUARIO(
  IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30),
  LOGIN VARCHAR(30),
  SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
  IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
  IDUSUARIO INT,
  NOME VARCHAR(30),
  LOGIN VARCHAR(30)
);
SHOW TABLES;
-- CRIANDO A TRIGGER
DELIMITER $
CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
  INSERT INTO BKP_USUARIO VALUES(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
$
DELIMITER ;

INSERT INTO USUARIO VALUES(NULL, 'LEONARDO', 'LEOSILVA', '12345678');
SELECT IDUSUARIO, NOME, LOGIN, SENHA FROM USUARIO;

DROP TRIGGER BACKUP_USER;

DELETE FROM USUARIO WHERE IDUSUARIO = 1;
SELECT IDBACKUP, IDUSUARIO, NOME, LOGIN FROM BKP_USUARIO;
