-- IDCLIENTE, NOME, SEXO, `E-MAIL`, NUMERO, TIPO, BAIRRO, CIDADE, ESTADO 
DROP TABLE ALUNOS;
CREATE TABLE ALUNOS(
    NUMERO INT,
    NOME VARCHAR(30)
);
SHOW TABLES;
DESC ALUNOS;

INSERT INTO ALUNOS(NUMERO, NOME) VALUES(1, 'JOAO');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(1, 'MARIA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(2, 'ZOE');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(2, 'ANDRE');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(3, 'CLARA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(1, 'CLARA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(4, 'MAFRA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(5, 'JANAINA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(1, 'JANAINA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(3, 'MARCELO');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(4, 'GIOVANNI');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(5, 'ANTONIO');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(6, 'ANA');
INSERT INTO ALUNOS(NUMERO, NOME) VALUES(6, 'VIVIANE');

SELECT NUMERO, NOME FROM ALUNOS;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY 1; -- SIGNIFICA COLUNA 1
SELECT NUMERO, NOME FROM ALUNOS ORDER BY 2; -- SIGNIFICA COLUNA 2

-- ORDERNANDO POR MAIS DE UMA COLUNA
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO, NOME;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY 1,2;

-- MESCLANDO ORDER BY COM PROJECAO
SELECT NOME FROM ALUNOS ORDER BY 1,2; -- ERROR 1054 (42S22): Unknown column '2' in 'order clause'
-- NÃO DÁ PARA ORDERNAR SEM PROJECAO DA COLUNA INDICANDO NÚMEROS DA COLUNA

-- CASE PRECISE ORDERNAR SEM PROJETAR A COLUNA INDIQUE O NOME DA COLUNA
SELECT NOME FROM ALUNOS ORDER BY NUMERO, NOME;

-- ORDER BY DESC / ASC
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO ASC;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO DESC;

SELECT NUMERO, NOME FROM ALUNOS ORDER BY NOME ASC;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NOME DESC;

SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO DESC, NOME DESC;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO DESC, NOME ASC;
SELECT NUMERO, NOME FROM ALUNOS ORDER BY NUMERO DESC, NOME;


-- ORDER BY EM JOINS
SELECT 
C.IDCLIENTE, C.NOME, C.SEXO, IFNULL(C.EMAIL, '********') AS 'E-MAIL',
T.TIPO, T.NUMERO,
E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE AS C 
INNER JOIN TELEFONE AS T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO AS E 
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY C.NOME;

SELECT 
C.IDCLIENTE, C.NOME, C.SEXO, IFNULL(C.EMAIL, '********') AS 'E-MAIL',
T.TIPO, T.NUMERO,
E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE AS C 
INNER JOIN TELEFONE AS T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO AS E 
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY C.EMAIL;

SELECT IDCLIENTE, NOME, SEXO, `E-MAIL`, NUMERO, TIPO, BAIRRO, CIDADE, ESTADO
FROM V_RELATORIO 
ORDER BY NOME;

SELECT IDCLIENTE, NOME, SEXO, `E-MAIL`, NUMERO, TIPO, BAIRRO, CIDADE, ESTADO
FROM V_RELATORIO 
ORDER BY SEXO;

SELECT IDCLIENTE, NOME, SEXO, `E-MAIL`, NUMERO, TIPO, BAIRRO, CIDADE, ESTADO
FROM V_RELATORIO 
ORDER BY TIPO;
