SHOW DATABASES;
USE PROJETO;
SHOW TABLES;
DESC CLIENTE;
SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL = NULL;

/* IS OU IS NOT NULL */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

