SHOW DATABASES;
USE PROJETO;
SHOW TABLES;
DESC CLIENTE;
SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM'; /* COMANDO ERRADO - FALTA WHERE*/
/* WHERE É MEGA IMPORTANTE */
SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE;

SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE WHERE NOME = 'LILIAN';


SELECT NOME, EMAIL FROM CLIENTE;


UPDATE CLIENTE SET EMAIL = 'JOAO@IG.COM.BR' WHERE NOME = 'JOAO';
UPDATE CLIENTE SET EMAIL = 'CELIA@GMAIL.COM' WHERE NOME = 'CELIA';
UPDATE CLIENTE SET EMAIL = 'JORGE@GLOBO.COM' WHERE NOME = 'JORGE';
UPDATE CLIENTE SET EMAIL = 'ANA@TERRA.COM.BR' WHERE NOME = 'ANA';
UPDATE CLIENTE SET EMAIL = 'CARLA@IG.COM.BR' WHERE NOME = 'CARLA';
UPDATE CLIENTE SET EMAIL = 'CLARA@IG.COM.BR' WHERE NOME = 'CLARA';