SHOW DATABASES;
USE PROJETO;
SHOW TABLES;
DESC CLIENTE;
SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE;

/* PERIGO */ DELETE FROM CLIENTE;
/*USE O DELETE JUNTO COM O WHERE SEMPRE */

SELECT COUNT(*) FROM CLIENTE;
/* 7 REGISTROS */

SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE WHERE NOME = 'JORGE';

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'JORGE'; /* 1 REGISTRO */

DELETE FROM CLIENTE WHERE NOME = 'JORGE';

INSERT INTO CLIENTE(NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO) 
VALUES('JORGE', '58748895', 'JORGE@GMAIL.COM', '11948000990', 'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER', 'M');

INSERT INTO CLIENTE(NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO) 
VALUES('JORGE', '58748895', 'JORGE@GLOBO.COM', '11948000990', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG', 'M');

SELECT NOME, EMAIL FROM CLIENTE WHERE NOME = 'JORGE' AND EMAIL = 'JORGE@GLOBO.COM';
DELETE FROM CLIENTE WHERE NOME = 'JORGE' AND EMAIL = 'JORGE@GLOBO.COM';