SHOW DATABASES;
USE COMERCIO;
SHOW TABLES;
DESC VENDEDORES;
/*
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| IDVENDEDOR | int         | NO   | PRI | NULL    | auto_increment |
| NOME       | varchar(30) | YES  |     | NULL    |                |
| SEXO       | char(1)     | YES  |     | NULL    |                |
| JANEIRO    | float(10,2) | YES  |     | NULL    |                |
| FEVEREIRO  | float(10,2) | YES  |     | NULL    |                |
| MARCO      | float(10,2) | YES  |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
*/

SELECT IDVENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO FROM VENDEDORES;

SELECT NOME FROM VENDEDORES;
SELECT MIN(MARCO) AS VALOR FROM VENDEDORES;
-- QUERY ERRADA ABAIXO 
SELECT NOME, MIN(MARCO) AS MIN_MARCO FROM VENDEDORES; -- this is incompatible with sql_mode=only_full_group_by

-- 1- VENDEDOR QUE VENDEU MENOS EM MARCO
-- 2- VENDEDOR QUE VENDEU MAIS EM MARCO
 

-- O NOME DO VENDEDOR DEVE SER SELECIONADO PELO VALOR MINIMO DO MÊS DE MARÇO
SELECT MIN(MARCO) FROM VENDEDORES; -- O MINIMO DE MARCO

-- QUERY COM INNER QUERY -- 1- VENDEDOR QUE VENDEU MENOS EM MARCO
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

-- INNER QUERY É TRAZIDO PRIMEIRO

-- 2- VENDEDOR QUE VENDEU MAIS EM MARCO
SELECT NOME, MARCO FROM VENDEDORES;
SELECT MAX(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

-- 3- QUEM VENDEU MAIS QUE O VALOR MEDIO DE FEVEREIRO
SELECT NOME, MARCO FROM VENDEDORES;
SELECT TRUNCATE(AVG(MARCO), 2) AS MEDIA FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO > (SELECT TRUNCATE(AVG(MARCO), 2) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES;
SELECT TRUNCATE(AVG(FEVEREIRO), 2) FROM VENDEDORES;
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT TRUNCATE(AVG(FEVEREIRO), 2) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES;
SELECT TRUNCATE(AVG(FEVEREIRO), 2) FROM VENDEDORES;
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO < (SELECT TRUNCATE(AVG(FEVEREIRO), 2) FROM VENDEDORES);


