/* FASE 1: Rascunho Conceitual */

CLIENTE - TABELA /* siga um padrão CLIENTE ou CLIENTES */

NOME - CARACTER(30)
CPF - CARACTER(11) /* USE CARACTER NO LUGAR DE NUMERICO */
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)


