/* FASE 3: MODELAGEM FISICA - SCRIPT DE BANCO */

/* Criando banco de Dados */
CREATE DATABASE PROJETO;
/* mostrando os bancos (só Mysql)*/
SHOW DATABASES;
/* CONECTANDO COM O BANCO */
USE PROJETO;

/* CRIANDO A TABELA CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	CPF VARCHAR(14),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	SEXO CHAR(1)
);

/* MOSTRANDO AS TABELAS */
SHOW TABLES;

/* DESCREVENDO A TABELA */
DESC CLIENTE;
