/* COMANDO SELECT */
SELECT NOW();
SELECT NOW() AS DATA_HORA, 'lEONARDO DE OLIVEIRA' AS professor;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT SEXO, EMAIL, ENDERECO, NOME FROM CLIENTE;

/*NÃO USE - NÃO IMPORTA COMO - NÃO USE*/
SELECT * FROM CLIENTE;
/* */

SELECT EMAIL, TELEFONE, CPF, NOW() AS DATA_HORA FROM CLIENTE;