/* COMANDO SELECT SELECIONANDO COM A CLAUSULA WHERE */
SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'F';
SELECT ENDERECO FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO = 'RJ'; /* RETORNA VAZIO */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ'; /* RETORNA VAZIO */
/* CARACTER CORINGA */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';/* % COMEÇA COM QUALQUER */
SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%OSCAR%';/* %% PESQUISA QUALQUER COINIDENCIA DO TERMO */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ%';/* % TERMINA COM */