SHOW DATABASES;
USE PROJETO;
SHOW TABLES;
DESC CLIENTE;
SELECT NOME, CPF, EMAIL, TELEFONE, ENDERECO, SEXO FROM CLIENTE;

SELECT TELEFONE FROM CLIENTE WHERE NOME = 'JOAO';

UPDATE CLIENTE SET TELEFONE = '978605434' WHERE NOME = 'JOAO';
UPDATE CLIENTE SET TELEFONE = '978605434 - 2467 6767' WHERE NOME = 'JOAO';

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE GROUP BY ENDERECO;