SHOW DATABASES;
USE COMERCIO;
SHOW TABLES;

CREATE TABLE TABELA(
  COLUNA1 VARCHAR(30),
  COLUNA2 VARCHAR(30),
  COLUNA3 VARCHAR(30)
);

DESC TABELA;
/*
+---------+-------------+------+-----+---------+-------+
| Field   | Type        | Null | Key | Default | Extra |
+---------+-------------+------+-----+---------+-------+
| COLUNA1 | varchar(30) | YES  |     | NULL    |       |
| COLUNA2 | varchar(30) | YES  |     | NULL    |       |
| COLUNA3 | varchar(30) | YES  |     | NULL    |       |
+---------+-------------+------+-----+---------+-------+
*/

-- ADD UMA PK -- NAO É POSSIVEL COLOCAR AUTO_INCREMENT NESTE COMANDO
ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1);
DESC TABELA;

-- ADD COLUNA SEM POSIÇAO => LAST POSITION
ALTER TABLE TABELA 
ADD COLUNA VARCHAR(30);
DESC TABELA;

ALTER TABLE TABELA 
ADD COLUNA100 INT(11);
DESC TABELA;

-- ADD COLUNA ESCOLHENDO UMA POSIÇÃO ESPECIFICA
ALTER TABLE TABELA 
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE 
AFTER COLUNA3;
DESC TABELA;

-- MODIFICANDO O TIPO DE UM CAMPO 
-- OBESERVAR DADOS DA COLUNA SE SAO OU PODEM SER COMPATIVEIS
ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;
DESC TABELA;


-- RENOMEANDO NOME DA TABELA
ALTER TABLE TABELA 
RENAME PESSOA;
SHOW TABLES;

CREATE TABLE TIME(
  IDTIME INT PRIMARY KEY AUTO_INCREMENT,
  TIME VARCHAR(30),
  ID_PESSOA VARCHAR(30)
);
SHOW TABLES;
DESC TIME;

-- ADD FK
ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

-- VERIFICANDO
SHOW CREATE TABLE TIME;
/*
| TIME  | CREATE TABLE `TIME` (
  `IDTIME` int NOT NULL AUTO_INCREMENT,
  `TIME` varchar(30) DEFAULT NULL,
  `ID_PESSOA` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`IDTIME`),
  KEY `ID_PESSOA` (`ID_PESSOA`),
  CONSTRAINT `time_ibfk_1` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`COLUNA1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/


