-- PROCEDIMENTOS ARMAZENADOS - STORAGE PROCEDURE
SELECT 'LEO';

DELIMITER $

CREATE PROCEDURE NOME()
BEGIN
    -- QUALQUER INSTRUÇAO SQL ;
END
$

-- CRIANDO UMA PROCEDURE
DELIMITER $
CREATE PROCEDURE NOME_EMPRESA()
BEGIN
    SELECT 'REVEWEB' AS EMPRESA;
END
$

-- CHAMANDO UMA PROCEDURE
CALL NOME_EMPRESA()$
DELIMITER ;
CALL NOME_EMPRESA;

-- PROCEDURE COM PARAMENTROS
SELECT 10 + 10 AS CONTA;

DELIMITER $
CREATE PROCEDURE CONTA()
BEGIN
    SELECT 10 + 10 AS CONTA;
END
$
DELIMITER ;

CALL CONTA();

-- APAGANDO UM PROCEDURE
DROP PROCEDURE CONTA;

-- RECRIANDO PROCEDURE CONTA COM 
DELIMITER $
CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
    SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$
DELIMITER ;

CALL CONTA(100, 50);