SELECT IDVENDEDOR, NOME, SEXO, JANEIRO, FEVEREIRO, MARCO FROM VENDEDORES;

SELECT TRUNCATE(SUM(JANEIRO),2) AS TOTAL_JAN FROM VENDEDORES;

SELECT 
    SUM(JANEIRO) AS TOTAL_JAN,
    SUM(FEVEREIRO) AS TOTAL_FEV,
    SUM(MARCO) AS TOTAL_MAR
FROM VENDEDORES;

-- VENDAS POR SEXO AGRUPADAS
SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO FROM VENDEDORES GROUP BY SEXO;
