/*
    DML = DATA MANIPULATION LANGUAGE
    DDL = DATA DEFINITION LANGUAGE
    DCL = DATA CONTROL LANGUAGE
    TCL - TRANSACTIONAL CONTOL LANGUAGE
*/


/* DML */
INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '999.999.999.99');
INSERT INTO ENDERECO VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7);
UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE = 7;
SELECT IDCLIENTE, NOME, SEXO  FROM CLIENTE;
/* FILTROS */
SELECT IDCLIENTE, NOME, SEXO FROM CLIENTE WHERE SEXO = 'F';
INSERT INTO CLIENTE VALUES(NULL, 'XXXX', 'M', NULL, 'XXX.XXX.XXX-XX');
SELECT IDCLIENTE, NOME, SEXO FROM CLIENTE WHERE IDCLIENTE = 8;
DELETE FROM CLIENTE WHERE IDCLIENTE = 8;
